Rek/version lock
osuosl-cookbooks/osl-mysql pull request #51
Opened 2020-09-24 00:48 UTC by TheREK3R

2020-09-24 19:11 UTC, ramereth requested changes

2020-09-24 19:11 UTC, ramereth commented on attributes/default.rb
> +default['percona']['version'] = '5.7' if node['platform_version'].to_i > 7
Please look at the default recipe..this isn't the correct way to do it. Also you'll need to update the tests.

2020-09-30 16:10 UTC, ramereth commented
@TheREK3R please fix the InSpec tests for the `client-percona-centos-8` suite? You might want to verify all of the other suites are working properly with EL8 as well.

2020-10-05 20:07 UTC, ramereth commented
@TheREK3R can you please rebase this against current master branch and also squash the commits? Please also fix the new cookstyle issus.

2020-10-07 04:06 UTC, ramereth approved these changes
Please do a patch bump.

2020-10-07 20:52 UTC, TheREK3R commented
!bump patch *

2020-10-07 21:29 UTC, TheREK3R commented
!bump patch *

2020-10-07 21:29 UTC, merged

2020-10-07 21:29 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v3.0.1.  Have a nice day!