alma 9 support
osuosl-cookbooks/osl-mysql pull request #87
Opened 2024-08-26 23:47 UTC by pasimko

2024-08-28 18:18 UTC, ramereth requested changes

2024-08-28 18:18 UTC, ramereth commented on kitchen.multi-node.yml
> +  flavor_ref: m1.medium
This shouldn't be needed. Can you please remove it?

2024-09-04 21:45 UTC, ramereth commented
!bump patch ~

2024-09-04 21:46 UTC, merged

2024-09-04 21:46 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v6.10.1.  Have a nice day!